# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tfstate-dish-mp-sbx"
    dynamodb_table = "tfstatelock-dish-mp-sbx"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
